# Generated by Django 5.2.1 on 2025-06-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('address_line1', models.CharField(max_length=255, verbose_name="Ligne d'adresse 1")),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ligne d'adresse 2")),
                ('postal_code', models.CharField(max_length=20, verbose_name='Code Postal')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='Belgique', max_length=100, verbose_name='Pays')),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de TVA')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro de téléphone')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de compte (IBAN)')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la banque')),
                ('bic_swift', models.CharField(blank=True, max_length=20, null=True, verbose_name='BIC/SWIFT')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name="Logo de l'entreprise")),
                ('terms_and_conditions', models.TextField(blank=True, null=True, verbose_name='Termes et conditions par défaut (pour factures)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Profil de l'Entreprise",
                'verbose_name_plural': "Profil de l'Entreprise",
            },
        ),
    ]
