# Generated by Django 5.2.1 on 2025-06-07 00:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0002_alter_companyprofile_options_companyprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='accent_color',
            field=colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None, verbose_name="Couleur d'accentuation"),
        ),
    ]
