# Generated by Django 5.2.1 on 2025-06-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom complet ou raison sociale du client', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Adresse email du client', max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, help_text='Adresse postale complète', null=True)),
                ('numero_tva', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de TVA')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
    ]
