# Generated by Django 5.2.4 on 2025-07-07 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom complet ou raison sociale du client', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Adresse email du client', max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone du client', max_length=20, null=True)),
                ('adresse_ligne1', models.CharField(help_text='Rue et numéro', max_length=255)),
                ('adresse_ligne2', models.CharField(blank=True, help_text="Ligne d'adresse supplémentaire (appartement, etc.)", max_length=255, null=True)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Belgique', max_length=100)),
                ('numero_tva', models.CharField(blank=True, help_text='Numéro de TVA (si applicable)', max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('user', 'nom')},
            },
        ),
    ]
