# Generated by Django 5.2.1 on 2025-06-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nom']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='adresse',
        ),
        migrations.AddField(
            model_name='client',
            name='adresse_ligne1',
            field=models.CharField(default='Adresse à compléter', help_text='Rue et numéro', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='adresse_ligne2',
            field=models.CharField(blank=True, help_text="Ligne d'adresse supplémentaire (appartement, etc.)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='code_postal',
            field=models.CharField(default='rue', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pays',
            field=models.CharField(default='Belgique', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(default='code_postal', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(help_text='Nom complet ou raison sociale du client', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_tva',
            field=models.CharField(blank=True, help_text='Numéro de TVA (si applicable)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone du client', max_length=20, null=True),
        ),
    ]
