# Generated by Django 5.2.1 on 2025-06-05 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_remove_client_adresse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(help_text='Nom complet ou raison sociale du client', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('user', 'nom')},
        ),
    ]
