# Generated by Django 5.2.1 on 2025-06-05 11:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_options_remove_client_adresse_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Numéro de facture unique', max_length=50, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text="Date d'émission de la facture")),
                ('due_date', models.DateField(help_text="Date d'échéance de la facture")),
                ('status', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Envoyée', 'Envoyée'), ('Payée', 'Payée'), ('En retard', 'En retard'), ('Annulée', 'Annulée')], default='Brouillon', help_text='Statut actuel de la facture', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Notes ou termes additionnels', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client associé à cette facture', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client')),
            ],
            options={
                'ordering': ['-issue_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="Description de l'article (peut être celle du produit ou personnalisée)", max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, help_text='Quantité facturée', max_digits=10)),
                ('unit_price_htva', models.DecimalField(decimal_places=2, help_text='Prix unitaire HTVA au moment de la facturation', max_digits=10)),
                ('invoice', models.ForeignKey(help_text='Facture à laquelle cet article appartient', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.invoice')),
                ('product', models.ForeignKey(help_text='Produit/Service facturé', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
