# Generated by Django 5.2.1 on 2025-06-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Numéro de facture unique (sera auto-généré si laissé vide)', max_length=50, unique=True),
        ),
    ]
