# Generated by Django 5.2.1 on 2025-07-07 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token d’accès public sécurisé pour cette note de crédit', unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token d’accès public sécurisé pour cette facture', unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token d’accès public sécurisé pour ce devis', unique=True),
        ),
    ]
