# Generated by Django 5.2.1 on 2025-06-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_amount_htva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Montant total HTVA (calculé)', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Montant total TTC (calculé)', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=21.0, help_text='Pourcentage de TVA appliqué (ex: 21.00)', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total_line_htva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total HTVA pour cette ligne (calculé)', max_digits=10),
            preserve_default=False,
        ),
    ]
