# Generated by Django 5.2.1 on 2025-06-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_invoice_total_amount_htva_invoice_total_amount_ttc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, help_text="Description de l'article (sera celle du produit si laissée vide)", max_length=255),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price_htva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire HTVA (sera celui du produit si laissé vide)', max_digits=10, null=True),
        ),
    ]
