# Generated by Django 5.2.1 on 2025-06-05 14:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_remove_client_adresse_and_more'),
        ('documents', '0004_alter_invoiceitem_description_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, help_text='Numéro de devis unique (sera auto-généré si laissé vide)', max_length=50, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text="Date d'émission du devis")),
                ('expiry_date', models.DateField(help_text="Date d'expiration du devis (validité)")),
                ('status', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Envoyé', 'Envoyé'), ('Accepté', 'Accepté'), ('Refusé', 'Refusé'), ('Expiré', 'Expiré')], default='Brouillon', help_text='Statut actuel du devis', max_length=10)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=21.0, help_text='Pourcentage de TVA appliqué (ex: 21.00)', max_digits=5)),
                ('total_amount_htva', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Montant total HTVA (calculé)', max_digits=10)),
                ('total_amount_ttc', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Montant total TTC (calculé)', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Termes ou notes spécifiques au devis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client associé à ce devis', on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='clients.client')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-issue_date', '-quote_number'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text="Description de l'article (sera celle du produit si laissée vide)", max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, help_text='Quantité proposée', max_digits=10)),
                ('unit_price_htva', models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire HTVA (sera celui du produit si laissé vide)', max_digits=10, null=True)),
                ('total_line_htva', models.DecimalField(blank=True, decimal_places=2, help_text='Total HTVA pour cette ligne (calculé)', max_digits=10)),
                ('product', models.ForeignKey(help_text='Produit/Service proposé', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('quote', models.ForeignKey(help_text='Devis auquel cet article appartient', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.quote')),
            ],
            options={
                'verbose_name': 'Ligne de Devis',
                'verbose_name_plural': 'Lignes de Devis',
                'ordering': ['id'],
            },
        ),
    ]
