# Generated by Django 5.2.1 on 2025-06-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_quote_quoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('Envoyé', 'Envoyé'), ('Accepté', 'Accepté'), ('Refusé', 'Refusé'), ('Expiré', 'Expiré'), ('Converti', 'Converti en Facture')], default='Brouillon', help_text='Statut actuel du devis', max_length=10),
        ),
    ]
