# Generated by Django 5.2.1 on 2025-06-05 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_quote_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Numéro de facture unique par utilisateur (sera auto-généré si laissé vide)', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(help_text="Description de l'article (peut être celle du produit ou personnalisée)", max_length=255),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price_htva',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Prix unitaire HTVA au moment de la facturation', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, help_text='Numéro de devis unique par utilisateur (sera auto-généré si laissé vide)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('user', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('user', 'quote_number')},
        ),
    ]
