# Generated by Django 5.2.1 on 2025-06-06 23:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_invoice_user_quote_user_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date du paiement')),
                ('payment_method', models.CharField(choices=[('Virement', 'Virement bancaire'), ('Carte', 'Carte de crédit'), ('Especes', 'Espèces'), ('Autre', 'Autre')], default='Virement', max_length=20, verbose_name='Méthode de paiement')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Référence ou note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(help_text='Facture associée à ce paiement', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='documents.invoice')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
            },
        ),
    ]
