# Generated by Django 5.2.1 on 2025-06-06 23:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_user_alter_client_nom_and_more'),
        ('documents', '0008_payment'),
        ('products', '0002_product_user_alter_product_nom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(blank=True, help_text='Numéro de la note de crédit (sera auto-généré si laissé vide)', max_length=50, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text="Date d'émission de la note de crédit")),
                ('status', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Finalisée', 'Finalisée')], default='Brouillon', max_length=10)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
                ('total_amount_htva', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount_ttc', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Raison de la note de crédit ou autres notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='clients.client')),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='documents.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note de Crédit',
                'verbose_name_plural': 'Notes de Crédit',
                'ordering': ['-issue_date', '-credit_note_number'],
                'unique_together': {('user', 'credit_note_number')},
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_price_htva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_line_htva', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.creditnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'Ligne de Note de Crédit',
                'verbose_name_plural': 'Lignes de Note de Crédit',
            },
        ),
    ]
