# Generated by Django 5.2.1 on 2025-06-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_creditnote_creditnoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantité facturée', max_digits=10),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantité proposée', max_digits=10),
        ),
    ]
