# Generated by Django 5.2.4 on 2025-07-07 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du produit ou du service', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description détaillée du produit ou service', null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix de vente unitaire hors TVA', max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('user', 'nom')},
            },
        ),
    ]
