# Generated by Django 5.2.1 on 2025-06-05 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='nom',
            field=models.CharField(help_text='Nom du produit ou du service', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('user', 'nom')},
        ),
    ]
